version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver:
        syslog
    restart:
      always

networks:
  default:
    external:
      name: common_link
