version: "2"

services:
  app:
    build: .
    container_name: nodebrew_app 
    volumes:
      - ./project:/home/appuser/app
    ports:
      - "4200:4200"
    command: bash -c "npm install && npm run start"