version: '2'
services:
  wordpress:
    image: wordpress
    environment:
      VIRTUAL_HOST: iskw.wordpress
      VIRTUAL_PORT: 8800
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
    volumes:
      - wordpress_db:/var/lib/mysql

volumes:
  wordpress_db:
    external: true

networks:
  default:
    external:
      name: common_link

