version: '2'
services:
  redmine:
    image: redmine
    environment:
      VIRTUAL_HOST: iskw.redmine
      VIRTUAL_PORT: 3000
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
    volumes:
      - redmine_files:/usr/src/redmine/files
    depends_on:
      - db
    restart:
      always

  db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    volumes:
      - redmine_db:/var/lib/mysql
    restart:
      always
    
volumes:
  redmine_files:
    external: true
  redmine_db:
    external: true

networks:
  default:
    external:
      name: common_link
