version: '2'

services:
  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mysql_db
      REDMINE_DB_PASSWORD: example
    volumes:
        - ./redmine-data/redmine:/usr/src/redmine/files
    depends_on:
      - mysql_db
    restart: always

  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
        - ./redmine-data/db:/var/lib/mysql
    restart: always
