version: '2'

services:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NGINX_PORT=80
    - NGINX_HOST=test.com
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./ssl:/etc/nginx.ssl
    - ./development.conf:/etc/nginx/conf.d/development.conf
    - nginx_log:/var/log/nginx

volumes:
  nginx_log:
    external: true
