version: "2"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: geo-dashboard-app
    #volumes:
    #  - ./project/:/home/appuser/app
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm run start"