FROM python:3.6

MAINTAINER K.Kato

RUN apt-get update \
    && apt-get install -y screen vim \
    && pip3 install --upgrade pip \
    && pip3 install --upgrade jupyter tensorflow pandas matplotlib seaborn scikit-learn